name: Publish  to npm

on:
    push:
        branches:
            - master

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      packages: read
      pull-requests: write
      checks: write

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm ci

      - name: Run build script
        run: npm run build --if-present

      - name: Execute tests
        run: npm test

      - name: Generate code coverage            
        run: npm run coverage

      - name: Validate code coverage
        uses: 5monkeys/cobertura-action@master
        with:
            path: coverage/cobertura-coverage.xml
            minimum_coverage: 85
      
      - name: Publish to npm
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          check-version: true
          greater-version-only: true